language: node_js

deploy:
  provider: heroku
  buildpack: https://github.com/ddollar/heroku-buildpack-multi.git
  api_key:
    secure: RYQZ+xozYqD5sJokJGxSl0ZHBEPY4Ea0Kuc6LFbUWuwIe8XHCDjK8UeAJbnSDoonmRXIte7ljhVpMeb72/L4Aew6vnp2jJPpOOcpHHrz6WtQiofsdK8PmVbJq1YY8nMT2YUgY6raXbV1RZmx8bacwtJeIne9ZdPwDJ5WqA8fPwrBEMHhvuYgwsr38AiP10DoHJ9qXkGcQUAIuGpQbFkBw/faXUJFkgZvGcQf4Tv9h4SxsVuYTbQk1rJQmRlYscQwdIldiRnziqVwHpYWb50paTfHlFVZlPZuBgysnIbkpN1UqJOUmDnawEabjncIHaLXKBXQWgtpNwbuybVXuKEljb6QZAADPSNfgkaRQnDr9fa7Y3x6P67n6fGhAcM3UUBZs+tNIsIAcyXU7XebsmLpVk1RNKFbhVCiNcSRD7Qp8Isg/iVtZrGFa72mwLNUz2WwFFg9fbdCKrTaF7KyuO09W2JCjsU41v5LdG3+M+dh/oxbAQa143LW2naI9u/djwnjvlmGidITZdJ1AImEmQMeB/CzZA8bt4QYz1e2gUq84Bh5qs3okdsyAn8Fb/+wwiHAbL3mxPkpE5CtUkxygoBT0ZWArLY5ne9nQF8ODZk5yVvgEdTsMHdtLOv6CDicikBdgmogKDzXOzrZUeji5Vbeh1iKI66lMmQHzYuDLOnHNE4=
  app: nginx-node-example
